---
general:
  site_name:
    client: true
    refresh: true
    default: Proyecto Granjas del Sur de Chile
    min: 1
    max: 50
    regex: ^[a-zA-Z0-9 ]*$
  allow_self_registration:
    client: true
    refresh: true
    default: true
    type: 'boolean'